### ISSUE TITLE
Please add instructions for the GAME_PARAMS env variable.

### ISSUE THREAD

**Issue by colonelmattyman** [ich777/docker-xonotic-server#2]
To load a server configuration file for a Xonotic server using ich777/docker-xonotic-server, you can use "+serverconfig server.cfg" in the GAME_PARAMS environment variable. This tells the server to load the server.cfg file found in the data directory, allowing you to apply custom server settings and configurations directly when launching the container. This is a useful tip for customizing the server's behaviour without modifying the container's default configuration files directly.

**Comment by colonelmattyman** [comment]
To load a server configuration file for a Xonotic server using ich777/docker-xonotic-server, you can use "+serverconfig server.cfg" in the GAME_PARAMS environment variable. This tells the server to load the server.cfg file found in the data directory, allowing you to apply custom server settings and configurations directly when launching the container. This is a useful tip for customizing the server's behaviour without modifying the container's default configuration files directly.

**Comment by ich777** [comment]
Description added.
